/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAfiliadoRouteImport } from './routes/_authenticated/afiliado'
import { Route as AuthenticatedDepositoRouteImport } from './routes/_authenticated/deposito'
import { Route as AuthenticatedJogoRouteImport } from './routes/_authenticated/jogo'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSaqueRouteImport } from './routes/_authenticated/saque'
import { Route as ApiGameConfigRouteImport } from './routes/api/game/config'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminAfiliadosRouteImport } from './routes/_authenticated/_admin/admin.afiliados'
import { Route as AuthenticatedAdminAdminAparenciaRouteImport } from './routes/_authenticated/_admin/admin.aparencia'
import { Route as AuthenticatedAdminAdminComissoesRouteImport } from './routes/_authenticated/_admin/admin.comissoes'
import { Route as AuthenticatedAdminAdminDemoRouteImport } from './routes/_authenticated/_admin/admin.demo'
import { Route as AuthenticatedAdminAdminDepositosRouteImport } from './routes/_authenticated/_admin/admin.depositos'
import { Route as AuthenticatedAdminAdminGatewayRouteImport } from './routes/_authenticated/_admin/admin.gateway'
import { Route as AuthenticatedAdminAdminHistoricoRouteImport } from './routes/_authenticated/_admin/admin.historico'
import { Route as AuthenticatedAdminAdminPapeisRouteImport } from './routes/_authenticated/_admin/admin.papeis'
import { Route as AuthenticatedAdminAdminPixelRouteImport } from './routes/_authenticated/_admin/admin.pixel'
import { Route as AuthenticatedAdminAdminRegrasRouteImport } from './routes/_authenticated/_admin/admin.regras'
import { Route as AuthenticatedAdminAdminRtpRouteImport } from './routes/_authenticated/_admin/admin.rtp'
import { Route as AuthenticatedAdminAdminSaquesRouteImport } from './routes/_authenticated/_admin/admin.saques'
import { Route as AuthenticatedAdminAdminUsuariosRouteImport } from './routes/_authenticated/_admin/admin.usuarios'
import { Route as AuthenticatedAdminAdminUsuariosIdRouteImport } from './routes/_authenticated/_admin/admin.usuarios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAfiliadoRoute = AuthenticatedAfiliadoRouteImport.update({
  id: '/afiliado',
  path: '/afiliado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositoRoute = AuthenticatedDepositoRouteImport.update({
  id: '/deposito',
  path: '/deposito',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogoRoute = AuthenticatedJogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaqueRoute = AuthenticatedSaqueRouteImport.update({
  id: '/saque',
  path: '/saque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiGameConfigRoute = ApiGameConfigRouteImport.update({
  id: '/api/game/config',
  path: '/api/game/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAfiliadosRoute =
  AuthenticatedAdminAdminAfiliadosRouteImport.update({
    id: '/admin/afiliados',
    path: '/admin/afiliados',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAparenciaRoute =
  AuthenticatedAdminAdminAparenciaRouteImport.update({
    id: '/admin/aparencia',
    path: '/admin/aparencia',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminComissoesRoute =
  AuthenticatedAdminAdminComissoesRouteImport.update({
    id: '/admin/comissoes',
    path: '/admin/comissoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDemoRoute =
  AuthenticatedAdminAdminDemoRouteImport.update({
    id: '/admin/demo',
    path: '/admin/demo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDepositosRoute =
  AuthenticatedAdminAdminDepositosRouteImport.update({
    id: '/admin/depositos',
    path: '/admin/depositos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminGatewayRoute =
  AuthenticatedAdminAdminGatewayRouteImport.update({
    id: '/admin/gateway',
    path: '/admin/gateway',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminHistoricoRoute =
  AuthenticatedAdminAdminHistoricoRouteImport.update({
    id: '/admin/historico',
    path: '/admin/historico',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPapeisRoute =
  AuthenticatedAdminAdminPapeisRouteImport.update({
    id: '/admin/papeis',
    path: '/admin/papeis',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPixelRoute =
  AuthenticatedAdminAdminPixelRouteImport.update({
    id: '/admin/pixel',
    path: '/admin/pixel',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminRegrasRoute =
  AuthenticatedAdminAdminRegrasRouteImport.update({
    id: '/admin/regras',
    path: '/admin/regras',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminRtpRoute =
  AuthenticatedAdminAdminRtpRouteImport.update({
    id: '/admin/rtp',
    path: '/admin/rtp',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSaquesRoute =
  AuthenticatedAdminAdminSaquesRouteImport.update({
    id: '/admin/saques',
    path: '/admin/saques',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminUsuariosRoute =
  AuthenticatedAdminAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminUsuariosIdRoute =
  AuthenticatedAdminAdminUsuariosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminAdminUsuariosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/afiliado': typeof AuthenticatedAfiliadoRoute
  '/deposito': typeof AuthenticatedDepositoRoute
  '/jogo': typeof AuthenticatedJogoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/saque': typeof AuthenticatedSaqueRoute
  '/api/game/config': typeof ApiGameConfigRoute
  '/admin/afiliados': typeof AuthenticatedAdminAdminAfiliadosRoute
  '/admin/aparencia': typeof AuthenticatedAdminAdminAparenciaRoute
  '/admin/comissoes': typeof AuthenticatedAdminAdminComissoesRoute
  '/admin/demo': typeof AuthenticatedAdminAdminDemoRoute
  '/admin/depositos': typeof AuthenticatedAdminAdminDepositosRoute
  '/admin/gateway': typeof AuthenticatedAdminAdminGatewayRoute
  '/admin/historico': typeof AuthenticatedAdminAdminHistoricoRoute
  '/admin/papeis': typeof AuthenticatedAdminAdminPapeisRoute
  '/admin/pixel': typeof AuthenticatedAdminAdminPixelRoute
  '/admin/regras': typeof AuthenticatedAdminAdminRegrasRoute
  '/admin/rtp': typeof AuthenticatedAdminAdminRtpRoute
  '/admin/saques': typeof AuthenticatedAdminAdminSaquesRoute
  '/admin/usuarios': typeof AuthenticatedAdminAdminUsuariosRouteWithChildren
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminAdminUsuariosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/afiliado': typeof AuthenticatedAfiliadoRoute
  '/deposito': typeof AuthenticatedDepositoRoute
  '/jogo': typeof AuthenticatedJogoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/saque': typeof AuthenticatedSaqueRoute
  '/api/game/config': typeof ApiGameConfigRoute
  '/admin/afiliados': typeof AuthenticatedAdminAdminAfiliadosRoute
  '/admin/aparencia': typeof AuthenticatedAdminAdminAparenciaRoute
  '/admin/comissoes': typeof AuthenticatedAdminAdminComissoesRoute
  '/admin/demo': typeof AuthenticatedAdminAdminDemoRoute
  '/admin/depositos': typeof AuthenticatedAdminAdminDepositosRoute
  '/admin/gateway': typeof AuthenticatedAdminAdminGatewayRoute
  '/admin/historico': typeof AuthenticatedAdminAdminHistoricoRoute
  '/admin/papeis': typeof AuthenticatedAdminAdminPapeisRoute
  '/admin/pixel': typeof AuthenticatedAdminAdminPixelRoute
  '/admin/regras': typeof AuthenticatedAdminAdminRegrasRoute
  '/admin/rtp': typeof AuthenticatedAdminAdminRtpRoute
  '/admin/saques': typeof AuthenticatedAdminAdminSaquesRoute
  '/admin/usuarios': typeof AuthenticatedAdminAdminUsuariosRouteWithChildren
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminAdminUsuariosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/afiliado': typeof AuthenticatedAfiliadoRoute
  '/_authenticated/deposito': typeof AuthenticatedDepositoRoute
  '/_authenticated/jogo': typeof AuthenticatedJogoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/saque': typeof AuthenticatedSaqueRoute
  '/api/game/config': typeof ApiGameConfigRoute
  '/_authenticated/_admin/admin/afiliados': typeof AuthenticatedAdminAdminAfiliadosRoute
  '/_authenticated/_admin/admin/aparencia': typeof AuthenticatedAdminAdminAparenciaRoute
  '/_authenticated/_admin/admin/comissoes': typeof AuthenticatedAdminAdminComissoesRoute
  '/_authenticated/_admin/admin/demo': typeof AuthenticatedAdminAdminDemoRoute
  '/_authenticated/_admin/admin/depositos': typeof AuthenticatedAdminAdminDepositosRoute
  '/_authenticated/_admin/admin/gateway': typeof AuthenticatedAdminAdminGatewayRoute
  '/_authenticated/_admin/admin/historico': typeof AuthenticatedAdminAdminHistoricoRoute
  '/_authenticated/_admin/admin/papeis': typeof AuthenticatedAdminAdminPapeisRoute
  '/_authenticated/_admin/admin/pixel': typeof AuthenticatedAdminAdminPixelRoute
  '/_authenticated/_admin/admin/regras': typeof AuthenticatedAdminAdminRegrasRoute
  '/_authenticated/_admin/admin/rtp': typeof AuthenticatedAdminAdminRtpRoute
  '/_authenticated/_admin/admin/saques': typeof AuthenticatedAdminAdminSaquesRoute
  '/_authenticated/_admin/admin/usuarios': typeof AuthenticatedAdminAdminUsuariosRouteWithChildren
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/usuarios/$id': typeof AuthenticatedAdminAdminUsuariosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/afiliado'
    | '/deposito'
    | '/jogo'
    | '/painel'
    | '/saque'
    | '/api/game/config'
    | '/admin/afiliados'
    | '/admin/aparencia'
    | '/admin/comissoes'
    | '/admin/demo'
    | '/admin/depositos'
    | '/admin/gateway'
    | '/admin/historico'
    | '/admin/papeis'
    | '/admin/pixel'
    | '/admin/regras'
    | '/admin/rtp'
    | '/admin/saques'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/usuarios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/afiliado'
    | '/deposito'
    | '/jogo'
    | '/painel'
    | '/saque'
    | '/api/game/config'
    | '/admin/afiliados'
    | '/admin/aparencia'
    | '/admin/comissoes'
    | '/admin/demo'
    | '/admin/depositos'
    | '/admin/gateway'
    | '/admin/historico'
    | '/admin/papeis'
    | '/admin/pixel'
    | '/admin/regras'
    | '/admin/rtp'
    | '/admin/saques'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/usuarios/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/_admin'
    | '/_authenticated/afiliado'
    | '/_authenticated/deposito'
    | '/_authenticated/jogo'
    | '/_authenticated/painel'
    | '/_authenticated/saque'
    | '/api/game/config'
    | '/_authenticated/_admin/admin/afiliados'
    | '/_authenticated/_admin/admin/aparencia'
    | '/_authenticated/_admin/admin/comissoes'
    | '/_authenticated/_admin/admin/demo'
    | '/_authenticated/_admin/admin/depositos'
    | '/_authenticated/_admin/admin/gateway'
    | '/_authenticated/_admin/admin/historico'
    | '/_authenticated/_admin/admin/papeis'
    | '/_authenticated/_admin/admin/pixel'
    | '/_authenticated/_admin/admin/regras'
    | '/_authenticated/_admin/admin/rtp'
    | '/_authenticated/_admin/admin/saques'
    | '/_authenticated/_admin/admin/usuarios'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/usuarios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiGameConfigRoute: typeof ApiGameConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/afiliado': {
      id: '/_authenticated/afiliado'
      path: '/afiliado'
      fullPath: '/afiliado'
      preLoaderRoute: typeof AuthenticatedAfiliadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposito': {
      id: '/_authenticated/deposito'
      path: '/deposito'
      fullPath: '/deposito'
      preLoaderRoute: typeof AuthenticatedDepositoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogo': {
      id: '/_authenticated/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof AuthenticatedJogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saque': {
      id: '/_authenticated/saque'
      path: '/saque'
      fullPath: '/saque'
      preLoaderRoute: typeof AuthenticatedSaqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/game/config': {
      id: '/api/game/config'
      path: '/api/game/config'
      fullPath: '/api/game/config'
      preLoaderRoute: typeof ApiGameConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/afiliados': {
      id: '/_authenticated/_admin/admin/afiliados'
      path: '/admin/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AuthenticatedAdminAdminAfiliadosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/aparencia': {
      id: '/_authenticated/_admin/admin/aparencia'
      path: '/admin/aparencia'
      fullPath: '/admin/aparencia'
      preLoaderRoute: typeof AuthenticatedAdminAdminAparenciaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/comissoes': {
      id: '/_authenticated/_admin/admin/comissoes'
      path: '/admin/comissoes'
      fullPath: '/admin/comissoes'
      preLoaderRoute: typeof AuthenticatedAdminAdminComissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/demo': {
      id: '/_authenticated/_admin/admin/demo'
      path: '/admin/demo'
      fullPath: '/admin/demo'
      preLoaderRoute: typeof AuthenticatedAdminAdminDemoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/depositos': {
      id: '/_authenticated/_admin/admin/depositos'
      path: '/admin/depositos'
      fullPath: '/admin/depositos'
      preLoaderRoute: typeof AuthenticatedAdminAdminDepositosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/gateway': {
      id: '/_authenticated/_admin/admin/gateway'
      path: '/admin/gateway'
      fullPath: '/admin/gateway'
      preLoaderRoute: typeof AuthenticatedAdminAdminGatewayRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/historico': {
      id: '/_authenticated/_admin/admin/historico'
      path: '/admin/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AuthenticatedAdminAdminHistoricoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/papeis': {
      id: '/_authenticated/_admin/admin/papeis'
      path: '/admin/papeis'
      fullPath: '/admin/papeis'
      preLoaderRoute: typeof AuthenticatedAdminAdminPapeisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/pixel': {
      id: '/_authenticated/_admin/admin/pixel'
      path: '/admin/pixel'
      fullPath: '/admin/pixel'
      preLoaderRoute: typeof AuthenticatedAdminAdminPixelRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/regras': {
      id: '/_authenticated/_admin/admin/regras'
      path: '/admin/regras'
      fullPath: '/admin/regras'
      preLoaderRoute: typeof AuthenticatedAdminAdminRegrasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/rtp': {
      id: '/_authenticated/_admin/admin/rtp'
      path: '/admin/rtp'
      fullPath: '/admin/rtp'
      preLoaderRoute: typeof AuthenticatedAdminAdminRtpRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/saques': {
      id: '/_authenticated/_admin/admin/saques'
      path: '/admin/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AuthenticatedAdminAdminSaquesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/usuarios': {
      id: '/_authenticated/_admin/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/usuarios/$id': {
      id: '/_authenticated/_admin/admin/usuarios/$id'
      path: '/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsuariosIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminUsuariosRoute
    }
  }
}

interface AuthenticatedAdminAdminUsuariosRouteChildren {
  AuthenticatedAdminAdminUsuariosIdRoute: typeof AuthenticatedAdminAdminUsuariosIdRoute
}

const AuthenticatedAdminAdminUsuariosRouteChildren: AuthenticatedAdminAdminUsuariosRouteChildren =
  {
    AuthenticatedAdminAdminUsuariosIdRoute:
      AuthenticatedAdminAdminUsuariosIdRoute,
  }

const AuthenticatedAdminAdminUsuariosRouteWithChildren =
  AuthenticatedAdminAdminUsuariosRoute._addFileChildren(
    AuthenticatedAdminAdminUsuariosRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminAfiliadosRoute: typeof AuthenticatedAdminAdminAfiliadosRoute
  AuthenticatedAdminAdminAparenciaRoute: typeof AuthenticatedAdminAdminAparenciaRoute
  AuthenticatedAdminAdminComissoesRoute: typeof AuthenticatedAdminAdminComissoesRoute
  AuthenticatedAdminAdminDemoRoute: typeof AuthenticatedAdminAdminDemoRoute
  AuthenticatedAdminAdminDepositosRoute: typeof AuthenticatedAdminAdminDepositosRoute
  AuthenticatedAdminAdminGatewayRoute: typeof AuthenticatedAdminAdminGatewayRoute
  AuthenticatedAdminAdminHistoricoRoute: typeof AuthenticatedAdminAdminHistoricoRoute
  AuthenticatedAdminAdminPapeisRoute: typeof AuthenticatedAdminAdminPapeisRoute
  AuthenticatedAdminAdminPixelRoute: typeof AuthenticatedAdminAdminPixelRoute
  AuthenticatedAdminAdminRegrasRoute: typeof AuthenticatedAdminAdminRegrasRoute
  AuthenticatedAdminAdminRtpRoute: typeof AuthenticatedAdminAdminRtpRoute
  AuthenticatedAdminAdminSaquesRoute: typeof AuthenticatedAdminAdminSaquesRoute
  AuthenticatedAdminAdminUsuariosRoute: typeof AuthenticatedAdminAdminUsuariosRouteWithChildren
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminAfiliadosRoute:
      AuthenticatedAdminAdminAfiliadosRoute,
    AuthenticatedAdminAdminAparenciaRoute:
      AuthenticatedAdminAdminAparenciaRoute,
    AuthenticatedAdminAdminComissoesRoute:
      AuthenticatedAdminAdminComissoesRoute,
    AuthenticatedAdminAdminDemoRoute: AuthenticatedAdminAdminDemoRoute,
    AuthenticatedAdminAdminDepositosRoute:
      AuthenticatedAdminAdminDepositosRoute,
    AuthenticatedAdminAdminGatewayRoute: AuthenticatedAdminAdminGatewayRoute,
    AuthenticatedAdminAdminHistoricoRoute:
      AuthenticatedAdminAdminHistoricoRoute,
    AuthenticatedAdminAdminPapeisRoute: AuthenticatedAdminAdminPapeisRoute,
    AuthenticatedAdminAdminPixelRoute: AuthenticatedAdminAdminPixelRoute,
    AuthenticatedAdminAdminRegrasRoute: AuthenticatedAdminAdminRegrasRoute,
    AuthenticatedAdminAdminRtpRoute: AuthenticatedAdminAdminRtpRoute,
    AuthenticatedAdminAdminSaquesRoute: AuthenticatedAdminAdminSaquesRoute,
    AuthenticatedAdminAdminUsuariosRoute:
      AuthenticatedAdminAdminUsuariosRouteWithChildren,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAfiliadoRoute: typeof AuthenticatedAfiliadoRoute
  AuthenticatedDepositoRoute: typeof AuthenticatedDepositoRoute
  AuthenticatedJogoRoute: typeof AuthenticatedJogoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSaqueRoute: typeof AuthenticatedSaqueRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAfiliadoRoute: AuthenticatedAfiliadoRoute,
  AuthenticatedDepositoRoute: AuthenticatedDepositoRoute,
  AuthenticatedJogoRoute: AuthenticatedJogoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSaqueRoute: AuthenticatedSaqueRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiGameConfigRoute: ApiGameConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
